name: kbook_elamri_zakariya
description: TechChallengeKentra-Flutter - EL AMRI ZAKARIYA

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.2
  dio: ^3.0.10
  equatable: ^1.2.4
  rxdart: ^0.24.1
  logger: ^0.9.2
  json_serializable: ^3.4.1
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.10




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/